
CREATE TABLE Cities (
	[Id] VARCHAR(36) NOT NULL PRIMARY KEY,
	[Name] VARCHAR(100) NOT NULL,
	[FederativeUnity] VARCHAR(2) NOT NULL,
	[PostalCode] VARCHAR(9) NOT NULL,
	[CreatedOn] DATETIME NOT NULL,
	[Deleted] BIT NOT NULL
);

CREATE TABLE Temperatures (
	[Id] VARCHAR(36) NOT NULL PRIMARY KEY,	
	[CityId] VARCHAR(36) NOT NULL FOREIGN KEY REFERENCES Cities(Id),
	[Value] REAL NOT NULL,
	[CreatedOn] DATETIME NOT NULL,
	[Deleted] BIT NOT NULL
);